# Generated by Django 4.0.3 on 2022-04-03 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='my_stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('UID', models.CharField(max_length=15, primary_key='True', serialize=False)),
                ('address', models.TextField(null='True')),
                ('available_bal', models.PositiveIntegerField(default=0)),
                ('invested_bal', models.PositiveIntegerField(default=0)),
                ('demat_ac', models.IntegerField()),
                ('bank_ac', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Prefer not to say')], default='M', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('uid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='uid', to='moneymarket.profile')),
            ],
        ),
    ]
