# Generated by Django 4.0.3 on 2022-04-03 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moneymarket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='uid',
        ),
        migrations.AddField(
            model_name='stock',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='uid', to=settings.AUTH_USER_MODEL),
        ),
    ]
