# Generated by Django 4.0.1 on 2022-04-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymarket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
