# Generated by Django 4.0.1 on 2022-03-31 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymarket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(null='True'),
            preserve_default='True',
        ),
    ]
