# Generated by Django 4.0.1 on 2022-03-31 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneymarket', '0002_user_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Client',
        ),
    ]
