# Generated by Django 4.0.1 on 2022-04-03 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moneymarket', '0002_my_stocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('UID', models.CharField(max_length=15, primary_key='True', serialize=False)),
                ('address', models.TextField(null='True')),
                ('available_bal', models.PositiveIntegerField(default=0)),
                ('invested_bal', models.PositiveIntegerField(default=0)),
                ('demat_ac', models.IntegerField()),
                ('bank_ac', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Prefer not to say')], default='M', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
