# Generated by Django 4.0.1 on 2022-03-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymarket', '0003_rename_user_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='idProof',
            field=models.ImageField(upload_to='Logos/Client_ID'),
        ),
    ]
