# Generated by Django 4.0.3 on 2022-04-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymarket', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_stocks',
            name='stock_symbol',
            field=models.CharField(max_length=50),
        ),
    ]
