# Generated by Django 4.0.3 on 2022-04-02 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneymarket', '0006_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='idProof',
        ),
    ]
