# Generated by Django 4.0.3 on 2022-04-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymarket', '0006_alter_my_stocks_stock_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='idProof',
            field=models.ImageField(null='True', upload_to='Logos/Client_ID'),
            preserve_default='True',
        ),
    ]
