# Generated by Django 4.0.3 on 2022-04-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymarket', '0007_profile_idproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='DOB',
            field=models.DateField(null='True'),
            preserve_default='True',
        ),
    ]
